### ISSUE TITLE
Clean up base PennyCollector class

### ISSUE THREAD

**Issue by swashcap** [MRN-Code/penny-collector#20]
- [ ] Convert to an ES6 class
- [ ] Move dynamic `require`s to top-level so that they’re static
- [ ] Clean up `PennyCollector#collect`: it’s putting the instance onto the passed-in options
- [ ] Examine and clean up inter-module dependencies (see watch.js and `PennyCollector#handleNewFile`)
- [ ] Clean up/remove iterator from `PennyCollector#handleNewFile`
- [ ]  Make `PennyCollector#handleNewFile` actually filter for specific file types
- [ ] Clean up `PennyCollector#validateFile`: it’s instantiating Halfpenny anew with every call. Also, its purpose is unclear.
- [ ] Add docblocks to methods

**Comment by swashcap** [comment]
This belongs in a design doc, but it’s related to the base class. So, here:

1. DICOM file gets put into watch path
2. `handleFile` calls the DICOM module
3. DICOM module parses the file and generates a metadata structure (penny.json)
4. `validateFile` (rename to `validatePenny` or the like) takes the penny.json and calls the API to see if the file metadata is correct.
  * **Incorrect:** penny meta and DICOM file are moved into lost-and-found such that they don't collide with other files. Study owners are notified.
  * **Correct:** File metadata is `POST`-ed to the API. The file _itself_ is posted to the API.
    * **Success:** Both the penny.json and the DICOM file are either deleted or moved to their preferred local destination

**Comment by jwtlake** [comment]
Regarding item 3. It seems we are actually creating a penny.json file. Is this even necessary? I would be inclined to keep everything in memory and create a penny object which could be passed around.

**Comment by swashcap** [comment]
@jwtlake: Yeah, agreed. This might be a caching technique in case the daemon goes blows up/errors out/etc.

**Comment by drewlandis** [comment]
I agree also, it would be nice to keep the metadata in memory/as an object rather than a penny.json file.  Ideally, if the daemon runs into a problem, we should record that to the log file and note the metadata details there.  I'd rather not cache those metadata details for later use as I could see that causing problems.

**Comment by swashcap** [comment]
@drewlandis I don’t think that’s a reason to not cache JSON. [Idiomatic Node error handling](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly) suggests killing the process upon error. Because of this we need to important program state is persisted such that we know file progress.

**Comment by drewlandis** [comment]
I agree that we should kill the process upon error.  We should log and then crash.

I don't think that we do need to know the file progress.  In order to keep PC stateless, we shouldn't cache the progress.  See the [flow diagram](https://www.draw.io/?state=%7B%22ids%22:%5B%220B6Dj_i0BNGAGSkFheFNkcWhjWHM%22%5D,%22action%22:%22open%22,%22userId%22:%22103030324433178696244%22%7D#G0B6Dj_i0BNGAGSkFheFNkcWhjWHM).  The way I envision it to happen is:
New file in watchpath > parse metadata > Check if metadata exists in DB, if not, save metadata to DB > archive locally > archive offsite > remove file from watchpath.
Even if it fails in the middle of the process, that's okay.  Upon restart, the penny collector will recognize the file is there and will attempt to process like normal.  It's okay we do any of the above steps multiple times.  (We need to decide if writing to archive multiple times should overwrite or cause an error.)
